#!/usr/bin/env python3
"""Write ENVIRONMENT.md from the RUNNING interpreter, never from memory.

    python scripts/23_export_environment.py            # print, do not write
    python scripts/23_export_environment.py --write    # write ENVIRONMENT.md

WHY THIS EXISTS
===============
A9. The NSCLC ISI is 0.318240180054566 on macOS/arm64 and 0.2964 on
Linux/x86_64 with the same seeds, the same pinned versions and inputs verified
byte-identical. A reader who reproduces a third number has no way to tell
whether they have hit A9 or their own environment drift. This file gives them
something to diff against.

WHY IT READS EVERYTHING LIVE
============================
Handoff #20 asserted that the macOS/HPC4 contrast was Accelerate-versus-
OpenBLAS. Measured, this Mac is **openblas 0.3.21**. That claim was plausible,
repeated across sessions, and wrong, and it survived only because nobody
printed the value. Every row below is therefore read from the interpreter at
run time. Nothing here is a literal, so nothing here can go stale silently.

NOT A SUBSTITUTE FOR THE VERSION CHECK
======================================
This script REPORTS. `20_check_versions.py` DECIDES: it compares the four
packages whose arithmetic reaches the estimand against requirements-lock.txt
and exits non-zero on drift. A report nobody diffs is not a check.
"""

from __future__ import annotations

import argparse
import importlib
import os
import platform
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Reported for context. The FOUR that 20_check_versions.py actually enforces
# are numpy, pandas, scikit-learn and scipy -- the ones whose arithmetic
# reaches the estimand. matplotlib and pyarrow render and load; they cannot
# move the number.
PACKAGES = ("numpy", "pandas", "scipy", "sklearn", "matplotlib", "pyarrow")

THREAD_VARS = ("OMP_NUM_THREADS", "VECLIB_MAXIMUM_THREADS",
               "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "PYTHONHASHSEED")


def blas_info() -> dict:
    """numpy's own record of what it was linked against.

    Wrapped because the `mode="dicts"` form is newer than some numpy builds and
    the shape of the dict is not guaranteed across versions. A missing key must
    print as `<unknown>` rather than raise -- an environment report that
    crashes on an unexpected environment is useless precisely when it matters.
    """
    try:
        import numpy
        return numpy.__config__.show(mode="dicts")["Build Dependencies"]["blas"]
    except Exception as exc:  # noqa: BLE001 - reporting tool, must not die
        return {"name": f"<unavailable: {type(exc).__name__}>"}


def git_commit() -> str:
    try:
        r = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"],
                           capture_output=True, text=True, check=True)
        return r.stdout.strip()
    except Exception:  # noqa: BLE001
        return "<not a git checkout>"


def render() -> str:
    b = blas_info()
    pkgs = {}
    for m in PACKAGES:
        try:
            pkgs[m] = importlib.import_module(m).__version__
        except Exception as exc:  # noqa: BLE001
            pkgs[m] = f"<not importable: {type(exc).__name__}>"

    rows_pkg = "\n".join(f"| {k} | {v} |" for k, v in pkgs.items())
    rows_thr = "\n".join(f"| `{v}` | {os.environ.get(v, '(unset)')} |"
                         for v in THREAD_VARS)

    return f"""# Exact environment that produced the frozen results

**Generated by `scripts/23_export_environment.py`. Every value below was read
from the running interpreter, not written from memory.** Regenerate with
`python scripts/23_export_environment.py --write`.

This file exists because of A9: the NSCLC ISI is 0.318240180054566 on this
platform and 0.2964 on Linux/x86_64 with the same pinned versions and
byte-identical inputs. A reader who reproduces a different number needs to be
able to tell whether they are seeing A9 or their own setup drift. Comparing
against this file is how.

## Platform

| | |
|---|---|
| system | {platform.system()} {platform.release()} |
| machine | {platform.machine()} |
| processor | {platform.processor() or "(not reported)"} |
| python | {sys.version.split()[0]} ({platform.python_implementation()}) |
| build | {" ".join(platform.python_build())} |
| compiler | {platform.python_compiler()} |
| git commit | `{git_commit()}` |

## BLAS -- the part A9 turns on

| | |
|---|---|
| name | **{b.get("name", "<unknown>")}** |
| version | **{b.get("version", "<unknown>")}** |
| detection | {b.get("detection method", "<unknown>")} |
| openblas config | {b.get("openblas configuration", "<unknown>")} |
| pc file | {b.get("pc file directory", "<unknown>")} |

**Handoff #20 asserted this contrast was Accelerate-vs-OpenBLAS. It is not.**
This machine is OpenBLAS, confirmed three independent ways. That wrong claim
survived several sessions because nobody printed it; this file prints it.

## Packages

| package | version |
|---|---|
{rows_pkg}

`scripts/20_check_versions.py` checks the four whose arithmetic reaches the
estimand (numpy, pandas, scikit-learn, scipy) against `requirements-lock.txt`
and exits non-zero on drift. The others are listed for context only and are
**NOT** checked -- if a fifth ever reaches the estimand, add it to that
script's watch list rather than relying on this file.

## Threading

**No BLAS thread-count variable is set for macOS runs, deliberately.** Thread
count changes floating-point reduction order, and A9 *is* a numerical
reproducibility investigation, so the environment is kept identical to the one
that produced the frozen results. The cluster sbatch scripts DO set them;
cluster numbers are diagnostic, never manuscript numbers.

Observed at generation time:

| variable | value |
|---|---|
{rows_thr}

`PYTHONHASHSEED=0` is exported by `reproduce.sh`, because str hashing is
randomised per process and gene-pool ordering must be deterministic. If it
reads `(unset)` above, this file was generated outside `reproduce.sh` -- that
does not affect any other value, but it is why the row is printed rather than
assumed.

## Seed audit

Every source of randomness in the pipeline, and where its seed is set.
**Re-derived 2026-09-05 by reading every call site, not by grep.** The previous
version of this table was written from a grep and listed four sources; there are
**twelve** `np.random.default_rng` call sites in `src/aacr27/`. All twelve are
deterministic, but six of them were undocumented and four take their seed from a
DEFAULT ARGUMENT rather than from `AuditConfig`, which is a weaker guarantee than
this table used to imply: they agree with the configured seed because
`seed: int = 0` happens to match `AuditConfig.seed = 0`, not because anything
wires them together. Changing `AuditConfig.seed` would silently NOT change them.

| source | call site | seeded by | notes |
|---|---|---|---|
| null gene-set draws | `signatures.py:353` | `AuditConfig.seed` (0) | per-signature nulls deliberately SHARE the seed, so two signatures of identical size and expression profile draw identical sets. Intentional for the family-level statistic; it means the 16 nulls are not independent (Limitations 7). |
| patient-clustered bootstrap | `stats.py:97` | `AuditConfig.seed` (0) | one patient set resampled per draw and shared across signatures, preserving between-signature correlation. |
| pooled-ISI bootstrap | `experiment.py:944` | `config.seed`, explicit | the pooled interval; passed the config directly. |
| Δr split-robustness bootstrap | `stats.py:135` | `config.seed`, explicit at `experiment.py:448` | `paired_delta`. Previously undocumented. |
| site-to-fold partition | `splits.py:171`, and `splits.py:64` for the stratified path | `AuditConfig.fold_seed` | a derived property, not a field: `experiment.py:137` returns `self.seed if self.split_seed is None else self.split_seed`, so the partition follows `seed` **unless** `split_seed` is set. Varied ONLY by `12_partition_variance.py`, which holds `seed` fixed so the spread it reports is attributable to the partition and nothing else. **The seed is not the whole story here — see A9 below.** |
| split-half reliability | `signatures.py:643` | explicit at `13_scorer_sensitivity.py:272`; default `seed=0` | the scorer-agnostic reliability used by A7's reconstruction. Previously undocumented. |
| Control C permutation calibration | `decomposition.py:393` | **DEFAULT `seed=0` only** — `11_close_science_gaps.py:177` passes no seed | deterministic, but not wired to `AuditConfig`. Previously undocumented. |
| ancestry Cramér's V calibration | `ancestry.py:127` | **DEFAULT `seed=0` only** — `06_run_ancestry.py:93` passes no seed | the identifiability result in Supplementary Table S1. Previously undocumented. |
| ancestry pooling | `ancestry.py:341` | **DEFAULT `seed=0` only** | Previously undocumented. |
| rotation null | *(no RNG)* | — | `stats.py:232` **consumes no randomness at all**: it reuses the already-drawn `null_r` matrix and computes a permutation p from it. The previous table listed it as "`AuditConfig.seed` (0), 1,000 draws", which was true of the draws it reads but wrong about the function, which is a pure transformation of its input. |
| str hashing / gene-pool order | — | `PYTHONHASHSEED=0` | exported by `reproduce.sh`. NOT set by default in an interactive shell -- see the table above. |

**What is NOT seeded, and does not need to be:** the ridge solve and
`scipy.stats.pearsonr` are deterministic given their inputs. That is precisely
why A9 is interesting -- with every seed pinned and the inputs hashed
identical, the answer still moves across platforms.

<!-- END GENERATED -- everything below this line is hand-authored.

     `test_environment_md_matches_a_fresh_render_on_this_platform` compares the
     committed file to a fresh `render()` only DOWN TO this marker. The sections
     below record things no machine can introspect: the second platform, and
     which non-stable sorts were load-bearing and why. Before this marker
     existed, adding either meant choosing between an accurate document and a
     green test, and the test would have lost. Keep new hand-authored material
     below the marker; keep anything derivable from the running interpreter
     above it, in `render()`, where it cannot go stale. -->
"""


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true",
                    help="write ENVIRONMENT.md instead of printing to stdout")
    args = ap.parse_args()
    text = render()
    if args.write:
        out = ROOT / "ENVIRONMENT.md"
        text = _splice(text, out)
        out.write_text(text)
        print(f"written to {out}")
    else:
        sys.stdout.write(text)
    return 0


MARKER = "<!-- END GENERATED"


def _splice(fresh: str, out) -> str:
    """Keep everything the existing file has BELOW the marker.

    MEASURED BUG, 2026-09-05: `--write` used to do `out.write_text(render())`,
    which silently deleted every hand-authored section below the marker. It
    destroyed the entire "Sort stability" section -- the A9/A10 record, the
    six-row table of every non-stable ordering and the guidance for anyone
    extending the pipeline -- and it was recovered only because the file was in
    git. The marker itself survived, because `render()` emits it, so a check
    that looked only for the marker reported success. That is precisely the
    shape of failure this project keeps meeting: the guard was present and the
    thing it guarded was gone.

    The contract the marker promises is "everything below this line is
    hand-authored", and a writer that honours it must therefore READ the file
    before overwriting it. If the file does not exist yet, or has no marker,
    the fresh render is written whole -- there is nothing to preserve.
    """
    if not out.exists():
        return fresh
    existing = out.read_text()
    if MARKER not in existing or MARKER not in fresh:
        return fresh
    return fresh[:fresh.index(MARKER)] + existing[existing.index(MARKER):]


if __name__ == "__main__":
    sys.exit(main())
